### ISSUE TITLE
Symbolic links are not recreated on container restart

### ISSUE THREAD

**Issue by hyperbolic2346** [tekgator/docker-mcmyadmin#1]
https://github.com/tekgator/docker-mcmyadmin/blob/a3eec68570b5ff62f7ff0d78f589e33dd2dbc0cd/usr/local/bin/app.sh#L22-L27

These lines create a symbolic link inside $INSTALL_PATH, /opt/app, which is inside the container. This link is lost on container restart and is not recreated. This makes the server not use the volume on subsequent runs. This should either be moved to the Dockerfile and baked into the image or the script changed to always make these symbolic links on startup. I'm not sure which way you would like to go here.

**Comment by tekgator** [comment]
It seemed to be worked for me just fine. Anyhow, I will have a look. I assume in the worst case this change will solve the problem?

```bash
function install_server {
 
    FIRST_RUN=0

    if [ ! -f McMyAdmin.conf ]; then
        FIRST_RUN=1
    fi
    
    mkdir -p $VOLUME_PATH/Minecraft
    mkdir -p $VOLUME_PATH/Backups
    mkdir -p $VOLUME_PATH/Exec
    mkdir -p $VOLUME_PATH/MCMA_Logs
    mkdir -p $VOLUME_PATH/Public

    touch $VOLUME_PATH/McMyAdmin.conf
    ln -nfs $VOLUME_PATH/McMyAdmin.conf $INSTALL_PATH
    ln -nfs $VOLUME_PATH/Minecraft $INSTALL_PATH
    ln -nfs $VOLUME_PATH/Backups $INSTALL_PATH
    ln -nfs $VOLUME_PATH/Exec $INSTALL_PATH
    ln -nfs $VOLUME_PATH/MCMA_Logs $INSTALL_PATH
    ln -nfs $VOLUME_PATH/Public $INSTALL_PATH

    if (( $FIRST_RUN > 0 ))
        echo -e "\nFirst start of the docker container start installation of McMyAdmin."
        echo "Please be patient, this will only take a few seconds!"

        cp $INSTALL_PATH/server.properties $VOLUME_PATH/Minecraft
        
        if [ "$EULA" == "1" ]; then
            echo -e "\nUser accepts EULA, create EULA.txt file."
            echo 'eula=true' > $VOLUME_PATH/Minecraft/eula.txt
        fi

        # unfortunately updating and setting the initial password cannot be combined, so two calls are made
        cd $INSTALL_PATH
        ./MCMA2_Linux_x86_64 -nonotice -updateonly
        ./MCMA2_Linux_x86_64 -configonly -setpass $MC_PWD

        # 1GB RAM is way to less to start running in a docker, therefore adjust conf to 2048 by default
        sed -i 's/Java.Memory=1024/Java.Memory=2048/g' $VOLUME_PATH/McMyAdmin.conf

        echo -e "\n************************************************************************" \
                "\n* Installation of McMyAdmin finished, access via http://localhost:8080 *" \
                "\n* Username: admin                                                      *" \
                "\n* Password: ${MC_PWD} (should be changed on first login)               *" \
                "\n************************************************************************\n"
    fi
}
```

**Comment by hyperbolic2346** [comment]
Thank you for looking into this.

I think your fix is close, but I think you need to copy the server.properties each time as well. To test this, create a volume and start the container. Then stop and delete the container and create another one and attach that volume again. The new container currently will not properly have the server properties and symlinks inside it.

Another option here is to configure the container so it always has those symlinks inside. Moving the symlinks into the Dockerfile would do that. Then you can reduce the complexity of your script.

**Comment by tekgator** [comment]
@hyperbolic2346 I've removed the need of the symbolic links. Tested it as you described, works just fine now.

If you like please try it out in the BETA channel `docker pull tekgator/docker-mcmyadmin:beta`

Please save your persistant data (e.g. Minecraft world) and start with a new volume.

**Comment by hyperbolic2346** [comment]
Thanks! I'll look into switching over to this. Thank you for putting in the time to fix this.
