### ISSUE TITLE
How can I run only the admin web service? 

### ISSUE THREAD

**Issue by Boxylmer** [tekgator/docker-mcmyadmin#10]
I have an existing docker image that has been modified and points to an existing volume. Can I use this image to provide an admin panel for the separately hosted server (I.e., run the admin service only without hosting the minecraft server) only? If so, how?

**Comment by tekgator** [comment]
Technically you could map your local minecraft to the minecraft folder within the container e.g. by adding:

`-v /home/minecraft/mcmyadmin/minecraft:/data/minecraft`

I'm not sure if it works, though. And I'm also not sure if it defeats the purpose of McMyAdmin.
Anyhow give it a try.

**Comment by Boxylmer** [comment]
Ah yes! I apologize, I should have updated with what I ended up doing. 

In docker-compose, I added the volume as the minecraft world data (as you suggested) and it worked perfectly! It fit our use case as well. I'll close this issue, but if anyone needs to know how to do this more verbosely, please reach out to me and I'll post a more thorough set of docker-compose instructions on how to do it (in the office now otherwise I would :P).
