### ISSUE TITLE
Having mcmyadmin running behind a reverse proxy

### ISSUE THREAD

**Issue by codebaard** [tekgator/docker-mcmyadmin#2]
I'm struggling to make the Docker Container work behind the https://github.com/nginx-proxy/nginx-proxy with the LetsEncrypt sidecar. 

- Before I introduced the proxy on my system, mcma was running with port 8082 exposed to the local interface and worked just fine.
- Then I introduced the reverse proxy and set up all my other services, which are working just fine, but mcma gives me a 502 - Bad Gateway. After trying back and forth I decided to at least temporarily switch back to the old setup, which was at least working.
- However - the old setup is now not working anymore. Even with the old unaltered docker-compose.yml, which was working before.

Except the Volume and the Port, I'm using the suggested compose from the Docker Repository:
``` bash
services:
  mcmyadmin:
    image: tekgator/docker-mcmyadmin
    container_name: mcmyadmin
    environment:
      PUID: 1001
      PGID: 100
      EULA: 1
    volumes:
      - /docker/minecraft/data/:/data
    ports:
      - 8082:8080
      - 25565:25565
    stop_grace_period: 30s
    restart: unless-stopped`
```
When I start the Container with `docker-compose up`, I get this log:

``` bash
Starting mcmyadmin ... done
Attaching to mcmyadmin
mcmyadmin    | Starting ./MCMA2_Linux_x86_64...
mcmyadmin    | ./MCMA2_Linux_x86_64 started.
mcmyadmin    |
mcmyadmin    | ************************************************************************
mcmyadmin    | * McMyAdmin started, access via http://localhost:8080                  *
mcmyadmin    | ************************************************************************
mcmyadmin    |
mcmyadmin    |
mcmyadmin    | ************************************************************************
mcmyadmin    | * Script is finished and going to sleep now, attaching to the log.     *
mcmyadmin    | ************************************************************************
mcmyadmin    |
mcmyadmin    | Console  : [21:54:01] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
mcmyadmin    | Console  : [21:54:02] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
mcmyadmin    | Console  : [21:54:02] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_nether
mcmyadmin    | Console  : [21:54:02] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
mcmyadmin    | Console  : [21:54:02] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_end
mcmyadmin    | Console  : [21:54:02] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
mcmyadmin    | Console  : [21:54:02] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
mcmyadmin    | Console  : [21:54:02] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
mcmyadmin    | Console  : [21:54:02] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
mcmyadmin    | Notice   : Minecraft server has stopped running.
```

If I'm trying to access mcma over the browser I get a _Connection Refused_. Nmap however shows that the port is open.

Since I'm inclined to solve the problem myself, I'd like to know a few things:

- Does starting up mcma with a different port/host configuration than before alter Settings in the data-directory?
- Is there some kind of setting to tweak to make it work behind the RP?
- Is there a way to at least restore the previous setup?

Thanks in advance,
J.

**Comment by tekgator** [comment]
Hello @codebaard,
I actually have it running behind a reverse proxy (Apache) as well, but the reverse proxy resides on another machine.

To answer your questions:

- No all default
- I don't use any special tweaks for my reverse proxy
- What has been altered in your setup? I assume your question could also be related to the other open [issue](https://github.com/tekgator/docker-mcmyadmin/issues/1).

**Comment by codebaard** [comment]
Thanks for your quick reply!

_I don't use any special tweaks for my reverse proxy_
Ok...thanks.

_What has been altered in your setup? I assume your question could also be related to the other open issue._
Might be. The thing is that the container worked just fine for two months, when I had it like `mydomain.com:8082`.
When I wanted to change everything to reverse proxy - essentially adding this to the docker-compose.yml:

``` bash
    environment:
      VIRTUAL_HOST: ${V_HOST}
      VIRTUAL_PORT: ${V_PORT}
      LETSENCRYPT_HOST: ${LE_HOST}
      LETSENCRYPT_EMAIL: ${LE_EMAIL}
    expose:
      - "8080"
    networks:
      - proxy
```
I just didn't work. When I wanted to revert everything to what it was, I stopped working altogether.

**However**: I also changed to URL from ```serverA.domain:8082``` to ```minecraft.serverB.domain```. Is there some kind of http-config within the image which causes problems?

Thanks for you help!

**Comment by ShiromMakkad** [comment]
I just wanted to say that I'm having the same issue, and I happen to also use port 8082 as well. I tried switching it to port 8080, but it didn't work

**Comment by tekgator** [comment]
I've modified the image and removed all symbolic links within. I'm not sure as this solves the actual problem, though because I've been running it under a Apache 2 reverse proxy without a problem.

Anyhow, if you like to try it out please pull the image from BETA channel `docker pull tekgator/docker-mcmyadmin:beta`

Please save your persistant data (e.g. Minecraft world) and start with a new volume.

**Comment by codebaard** [comment]
I'll check it out! ...Thanks for the effort. I'll get back to you next week.

**Comment by tekgator** [comment]
I actually believe it should solve your problem. See #1 ...
When you changing the port it is recreating the container and therefore all the symbolic links were broken.

So let me know if that was the issue.
