### ISSUE TITLE
Older Version of Java

### ISSUE THREAD

**Issue by MrCatters** [tekgator/docker-mcmyadmin#5]
When attempting to use Minecraft version 1.17, I receive an error message from the console stating that the jar file can not be ran due to it being compiled by an older version of Java.

[mcmyadmin_logs.txt](https://github.com/tekgator/docker-mcmyadmin/files/6619164/_mcmyadmin_logs.txt)

When using 1.16.5, this issue does not occur. I have already tried to completely remove the container and all file associated with it and perform a fresh reinstall with no luck.

**Comment by truedeity** [comment]
Yeah I got the same issue.  The server needs to have Java version 16.0 which is a bleeding edge version of java.

**Comment by tekgator** [comment]
Will compile a version with Java 16 tomorrow.

**Comment by tekgator** [comment]
New version is online, just get latest version or v2.1.0 and you will be up and running.

**Comment by truedeity** [comment]
DId you test this by chance?  

I just tried it but when I connect to the sever I get this

root@615e520f93f7:/data# java -version
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment 18.9 (build 11.0.10+9)

**Comment by tekgator** [comment]
Are you sure you pulled the last version? Working fine for me....

Server v1.17
![image](https://user-images.githubusercontent.com/11077551/121581697-6d8a0400-ca2e-11eb-9172-daa362587454.png)

Client v1.17
![image](https://user-images.githubusercontent.com/11077551/121582233-0b7dce80-ca2f-11eb-86a8-26ad6cc4aacd.png)

**Comment by truedeity** [comment]
I just created the docker container like so-

docker run -d \
  --name mcmyadmin \
  -p 8080:8080 \
  -p 25565:25565 \
  -v /home/minecraft/mcmyadmin:/data \
  -e PUID=1000 \
  -e PGID=100 \
  -e EULA=1 \
  --restart unless-stopped  \
  --stop-timeout 30 \
  tekgator/docker-mcmyadmin:latest

**Comment by truedeity** [comment]
actually my docker did not pull the latest version.  the fix worked.  thank you.

**Comment by tekgator** [comment]
If you run it this way you must delete or update the old image first. This can be achieved either by running
`docker image rm -f tekgator/docker-mcmyadmin`
or
`docker pull tekgator/docker-mcmyadmin`

Afterwards you can execute the run command again.
