### ISSUE TITLE
1.18 Java file has been compiled by a more recent version of Java Runtime

### ISSUE THREAD

**Issue by bradyj04** [tekgator/docker-mcmyadmin#6]
It works on another computer with JDK 17 installed, is there any way to update it?

**Comment by BadgerHobbs** [comment]
I've created a pull request https://github.com/tekgator/docker-mcmyadmin/pull/7 fixing this issue

**Comment by tekgator** [comment]
Pull request #7 merged, thanks to @BadgerHobbs. Only problem docker image is not built automatically anymore since docker changed their conditions. You will have to build yourself.
