### ISSUE TITLE
CONSOLE: has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 60.0

### ISSUE THREAD

**Issue by wrudwulf** [tekgator/docker-mcmyadmin#8]
After updating MC server inside MCMyAdmin, server fails to start.
Already tried to update Java inside container, but no luck

**Comment by tekgator** [comment]
Please pull the latest version of the image (latest or v2.2.0) from DockerHub which solves the issue.

Duplicate of #7
