### ISSUE TITLE
arm support

### ISSUE THREAD

**Issue by l0u1sg** [tekgator/docker-mcmyadmin#9]
Hello,

Is there an arm version of your Docker image or is it planned?

Thanks to you !

**Comment by tekgator** [comment]
I will have a look at it. Don't have an ARM device so lets see how to test. 
I guess it could be as easy as change the first line in the Dockerfile from

`FROM openjdk:17-jdk-slim-buster`
to 
`FROM arm64v8/openjdk:17-jdk-slim-buster`

and rebuild the image. Will have a look at the weekend.

**Comment by l0u1sg** [comment]
I tried to change the base image, but I think it's McMyAdmin that's the problem now. I don't see an ARM version of their image on their site

```
/app/app.sh: line 21: ./MCMA2_Linux_x86_64: cannot execute binary file: Exec format error
User accepts EULA
'/app/config/Minecraft/eula.txt' -> './Minecraft/eula.txt'
'/app/config/Minecraft/server.properties' -> './Minecraft/server.properties'
'/app/config/Minecraft' -> './Minecraft'
'/app/config/McMyAdmin.conf' -> './McMyAdmin.conf'
'/app/config/MCMA2_Linux_x86_64' -> './MCMA2_Linux_x86_64'
changed ownership of '/data' from root:root to 9001:9001
Please be patient, this will only take a few minutes!
First start of the docker container start installation of McMyAdmin.
```

**Comment by tekgator** [comment]
Yes just checked, unfortunately no ARM version for McMyAdmin available. 
[CubeCoders AMP](https://cubecoders.com/AMP) has an ARM version, I just never got the hang of AMP really thats why I'm stuck with McMyAdmin.

Closing this issue.
